apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    deployment: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: momos
      type: backend
  template:
    metadata:
      labels:
        app: momos
        type: backend
    spec:
      containers:
      - name: django
        image: 985991030409.dkr.ecr.us-east-1.amazonaws.com/momos-backend:lastest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000

