apiVersion: v1
kind: Pod
metadata:
  name: momos-django-api-pod
  labels:
    app: momos
    type: backend
spec:
  containers:
    - name: django-container-momos
      image: 985991030409.dkr.ecr.us-east-1.amazonaws.com/momos-backend:lastest
      readinessProbe:
        httpGet:
          path: /
          port: 9000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSecods: 15
