apiVersion: v1
kind: Service
metadata:
  name: momos-django-api-service
  labels:
    app: momos
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: api
    - port: 80
      targetPort: 80
      name: static
  selector:
    app: momos
    type: backend